site_name: My Docs
theme:
  name: material
  features:
  - content.code.copy
plugins:
  - search
  - mkdocstrings
markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
nav:
  - Home: index.md
  - Usage: usage.md
  - Read Lidar: read_lidar.md
  - Functions: functions.md